export enum SessionStatus {
   SCHEDULED = "SCHEDULED",
   CONFIRMED = "CONFIRMED",
   REJECTED = "REJECTED",
   CANCELLED = "CANCELLED",
   COMPLETED = "COMPLETED",
   NOT_CONDUCTED = "NOT_CONDUCTED",
   DISPUTED = "DISPUTED",
}

export const SESSION_STATUS_VALUES = Object.values(SessionStatus);
